[package]
name = "metrics_distributor"
version = "0.2.3"
authors = ["Dirk Gadsden <dirk@esherido.com>"]
description = "Ingest logs and forward aggregated data to APIs/services."
license = "BSD-3-Clause"
repository = "https://github.com/dirk/metrics_distributor"

[dependencies]
hyper = "0.7.2"
iron = "0.2.6"
router = "0.1.0"
regex = "0.1.55"
lazy_static = "0.1.15"
nom = "1.2.0"
chrono = "0.2.19"
rustc-serialize = "0.3.18"

[[example]]
name = "http_server"

[[example]]
name = "statsd_server"
